apiVersion: platform.meridian.io/v1alpha1
kind: XNetwork
metadata:
  name: dev-vpc-1
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    terasky.backstage.io/source-file-url: https://github.com/lordpangan/platform-gitops/blob/main/infra-requests/dev-vpc-1.yaml
spec:
  mode: dev
  tags:
    owner: platform-team
    env: dev
    Test: adding-tags
