apiVersion: platform.meridian.io/v1alpha1
kind: XNetwork
metadata:
  name: dev-vpc-2
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    terasky.backstage.io/owner: group:default/guests
    terasky.backstage.io/system: dev
    terasky.backstage.io/source-file-url: https://github.com/lordpangan/platform-gitops/blob/main/infra-requests/dev-vpc-2.yaml
spec:
  mode: dev
